/*
===============================================================================
File Name  : learning_course_content_details.sql
Module     : Oracle Fusion HCM - Learning
Description:
This report extracts Course, Offering, and Content details from Oracle Learning
Cloud including content title, content type, tracking type, author, status,
external identifier, and creator information.

Author     : Madhukar
Created    : 2026
===============================================================================
*/

SELECT DISTINCT

       WLIFT_COURSE.NAME COURSE_NAME,
       WLIF_COURSE.LEARNING_ITEM_NUMBER COURSE_NUMBER,

       WLIFT_CONTENT.NAME CONTENT_TITLE,
       WLIF_CONTENT.LEARNING_ITEM_ID CONTENT_ID,
       WLIF_CONTENT.LEARNING_ITEM_NUMBER CONTENT_NUMBER,

       WLCF.CONTENT_TYPE CONTENT_TYPE,
       WLCF.AUTHOR AUTHOR,

       FLV.MEANING STATUS,
       FLV1.MEANING TRACKING_TYPE,

       WLCF.EXTERNAL_IDENTIFIER EXTERNAL_IDENTIFIER,
       WLIFT_CONTENT.DESCRIPTION DESCRIPTION,

       (
           SELECT PPNF.DISPLAY_NAME
           FROM PER_PERSON_NAMES_F PPNF,
                PER_ALL_PEOPLE_F PAPF
           WHERE PPNF.PERSON_ID = PAPF.PERSON_ID
           AND PAPF.PERSON_NUMBER = WLIF_CONTENT.CREATED_BY
           AND SYSDATE BETWEEN PAPF.EFFECTIVE_START_DATE
                           AND PAPF.EFFECTIVE_END_DATE
           AND SYSDATE BETWEEN PPNF.EFFECTIVE_START_DATE
                           AND PPNF.EFFECTIVE_END_DATE
           AND NAME_TYPE = 'GLOBAL'
       ) CREATED_BY

FROM

     WLF_LI_ACTIVITIES_F WLAF,
     WLF_LEARNING_ITEMS_F_TL WLIFT_OFFERING,
     WLF_LEARNING_ITEMS_F WLIF_OFFERING,

     WLF_LEARNING_ITEMS_F_TL WLIFT_CONTENT,
     WLF_LEARNING_ITEMS_F WLIF_CONTENT,

     WLF_LI_CONTENT_F WLCF,

     FND_LOOKUP_VALUES FLV,
     FND_LOOKUP_VALUES FLV1,

     WLF_LI_CLASSES_F WLCLF,

     WLF_LEARNING_ITEMS_F WLIF_COURSE,
     WLF_LEARNING_ITEMS_F_TL WLIFT_COURSE

WHERE 1 = 1

AND FLV.LOOKUP_CODE = WLIF_CONTENT.STATUS
AND FLV1.LOOKUP_CODE = WLCF.TRACKING_TYPE

AND WLIF_CONTENT.LEARNING_ITEM_ID = WLCF.LEARNING_ITEM_ID

AND WLAF.PARENT_LEARNING_ITEM_ID = WLIFT_OFFERING.LEARNING_ITEM_ID
AND WLIFT_OFFERING.LEARNING_ITEM_ID = WLIF_OFFERING.LEARNING_ITEM_ID

AND WLIF_CONTENT.LEARNING_ITEM_ID = WLIFT_CONTENT.LEARNING_ITEM_ID
AND WLIF_CONTENT.LEARNING_ITEM_ID = WLAF.RELATED_CONTENT_ID

AND WLCLF.LEARNING_ITEM_ID = WLIFT_OFFERING.LEARNING_ITEM_ID

AND WLIFT_COURSE.LEARNING_ITEM_ID = WLCLF.COURSE_LEARNING_ITEM_ID
AND WLIF_COURSE.LEARNING_ITEM_ID = WLIFT_COURSE.LEARNING_ITEM_ID

AND WLIF_OFFERING.LEARNING_ITEM_TYPE = 'ORA_CLASS'
AND WLIF_COURSE.LEARNING_ITEM_TYPE = 'ORA_COURSE'

AND FLV1.LOOKUP_TYPE = 'ORA_WLF_CO_TRACKING_TYPE'

AND WLIFT_OFFERING.LANGUAGE = USERENV('LANG')
AND FLV.LANGUAGE = USERENV('LANG')
AND FLV1.LANGUAGE = USERENV('LANG')

AND SYSDATE BETWEEN WLIF_COURSE.EFFECTIVE_START_DATE
                AND WLIF_COURSE.EFFECTIVE_END_DATE

AND SYSDATE BETWEEN WLIFT_COURSE.EFFECTIVE_START_DATE
                AND WLIFT_COURSE.EFFECTIVE_END_DATE

AND SYSDATE BETWEEN WLCLF.EFFECTIVE_START_DATE
                AND WLCLF.EFFECTIVE_END_DATE

AND SYSDATE BETWEEN WLIF_OFFERING.EFFECTIVE_START_DATE
                AND WLIF_OFFERING.EFFECTIVE_END_DATE

AND SYSDATE BETWEEN WLIFT_OFFERING.EFFECTIVE_START_DATE
                AND WLIFT_OFFERING.EFFECTIVE_END_DATE

AND SYSDATE BETWEEN WLIFT_CONTENT.EFFECTIVE_START_DATE
                AND WLIFT_CONTENT.EFFECTIVE_END_DATE

AND SYSDATE BETWEEN WLIF_CONTENT.EFFECTIVE_START_DATE
                AND WLIF_CONTENT.EFFECTIVE_END_DATE

AND SYSDATE BETWEEN WLAF.EFFECTIVE_START_DATE
                AND WLAF.EFFECTIVE_END_DATE


AND (
      WLIFT_CONTENT.LEARNING_ITEM_ID IN (:CONTENT_NAME)
      OR LEAST(:CONTENT_NAME) IS NULL
    )

AND (
      FLV.MEANING IN (:STATUS)
      OR LEAST(:STATUS) IS NULL
    );
